//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * All informations which detailed the trade
 * 
 * <p>Java class for AffirmationCustodyAdditionnalTradeInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AffirmationCustodyAdditionnalTradeInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.rbcdexia.com}DepositoryRef" minOccurs="0"/>
 *         &lt;element name="Allocations" type="{http://www.rbcdexia.com}AllocationBlockDetailsType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}CrossRefNbr" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}BankNbr" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}DKReason" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}StateYield" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AffirmationCustodyAdditionnalTradeInformationType", propOrder = {
    "depositoryRef",
    "allocations",
    "crossRefNbr",
    "bankNbr",
    "dkReason",
    "stateYield"
})
public class AffirmationCustodyAdditionnalTradeInformationType {

    @XmlElement(name = "DepositoryRef")
    protected String depositoryRef;
    @XmlElement(name = "Allocations")
    protected AllocationBlockDetailsType allocations;
    @XmlElement(name = "CrossRefNbr")
    protected String crossRefNbr;
    @XmlElement(name = "BankNbr")
    protected String bankNbr;
    @XmlElement(name = "DKReason")
    protected String dkReason;
    @XmlElement(name = "StateYield")
    protected BigDecimal stateYield;

    /**
     * Gets the value of the depositoryRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositoryRef() {
        return depositoryRef;
    }

    /**
     * Sets the value of the depositoryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositoryRef(String value) {
        this.depositoryRef = value;
    }

    /**
     * Gets the value of the allocations property.
     * 
     * @return
     *     possible object is
     *     {@link AllocationBlockDetailsType }
     *     
     */
    public AllocationBlockDetailsType getAllocations() {
        return allocations;
    }

    /**
     * Sets the value of the allocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocationBlockDetailsType }
     *     
     */
    public void setAllocations(AllocationBlockDetailsType value) {
        this.allocations = value;
    }

    /**
     * Gets the value of the crossRefNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossRefNbr() {
        return crossRefNbr;
    }

    /**
     * Sets the value of the crossRefNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossRefNbr(String value) {
        this.crossRefNbr = value;
    }

    /**
     * Gets the value of the bankNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankNbr() {
        return bankNbr;
    }

    /**
     * Sets the value of the bankNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankNbr(String value) {
        this.bankNbr = value;
    }

    /**
     * Gets the value of the dkReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDKReason() {
        return dkReason;
    }

    /**
     * Sets the value of the dkReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDKReason(String value) {
        this.dkReason = value;
    }

    /**
     * Gets the value of the stateYield property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStateYield() {
        return stateYield;
    }

    /**
     * Sets the value of the stateYield property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStateYield(BigDecimal value) {
        this.stateYield = value;
    }

}
