//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Cancel Type
 * 
 * <p>Java class for CANCELType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CANCELType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.rbcdexia.com}RelatedRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}LinkOpeTyp" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}LinkedRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}Reason" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CANCELType", propOrder = {

})
public class CANCELType {

    @XmlElement(name = "RelatedRef")
    protected String relatedRef;
    @XmlElement(name = "LinkOpeTyp")
    protected String linkOpeTyp;
    @XmlElement(name = "LinkedRef")
    protected String linkedRef;
    @XmlElement(name = "Reason")
    protected String reason;

    /**
     * Gets the value of the relatedRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedRef() {
        return relatedRef;
    }

    /**
     * Sets the value of the relatedRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedRef(String value) {
        this.relatedRef = value;
    }

    /**
     * Gets the value of the linkOpeTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkOpeTyp() {
        return linkOpeTyp;
    }

    /**
     * Sets the value of the linkOpeTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkOpeTyp(String value) {
        this.linkOpeTyp = value;
    }

    /**
     * Gets the value of the linkedRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedRef() {
        return linkedRef;
    }

    /**
     * Sets the value of the linkedRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedRef(String value) {
        this.linkedRef = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

}
