//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Domain-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Domain-Type">
 *   &lt;restriction base="{http://www.rbcdexia.com}A">
 *     &lt;maxLength value="2"/>
 *     &lt;enumeration value="GC"/>
 *     &lt;enumeration value="FA"/>
 *     &lt;enumeration value="TA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Domain-Type")
@XmlEnum
public enum DomainType {

    GC,
    FA,
    TA;

    public String value() {
        return name();
    }

    public static DomainType fromValue(String v) {
        return valueOf(v);
    }

}
