//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Exchange Rate : The exchange rate agreed to by the client and the broker when the trade currency differs from the settlement currency.
 * 
 * <p>Java class for ExchangeRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExchangeRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromCcy" type="{http://www.rbcdexia.com}A3" minOccurs="0"/>
 *         &lt;element name="ToCcy" type="{http://www.rbcdexia.com}A3" minOccurs="0"/>
 *         &lt;element name="ExchRate" type="{http://www.rbcdexia.com}N" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeRateType", propOrder = {
    "fromCcy",
    "toCcy",
    "exchRate"
})
public class ExchangeRateType {

    @XmlElement(name = "FromCcy")
    protected String fromCcy;
    @XmlElement(name = "ToCcy")
    protected String toCcy;
    @XmlElement(name = "ExchRate")
    protected BigDecimal exchRate;

    /**
     * Gets the value of the fromCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCcy() {
        return fromCcy;
    }

    /**
     * Sets the value of the fromCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCcy(String value) {
        this.fromCcy = value;
    }

    /**
     * Gets the value of the toCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCcy() {
        return toCcy;
    }

    /**
     * Sets the value of the toCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCcy(String value) {
        this.toCcy = value;
    }

    /**
     * Gets the value of the exchRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchRate() {
        return exchRate;
    }

    /**
     * Sets the value of the exchRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchRate(BigDecimal value) {
        this.exchRate = value;
    }

}
