//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Other Party Definition Type :
 * 			In case of use "MF/Focus internal code Z" instead of BIC Code.
 * 			Or if using a "US Fedwire" or "Canadian Code" instead of BIC code.
 * 
 * <p>Java class for OTHERPARTYDEFINITIONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTHERPARTYDEFINITIONType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.rbcdexia.com}InternalPtyType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}InternalPtyId" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}InternalPtyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}InternalPtyAddress" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTHERPARTYDEFINITIONType", propOrder = {
    "internalPtyType",
    "internalPtyId",
    "internalPtyName",
    "internalPtyAddress"
})
public class OTHERPARTYDEFINITIONType {

    @XmlElement(name = "InternalPtyType")
    protected String internalPtyType;
    @XmlElement(name = "InternalPtyId")
    protected String internalPtyId;
    @XmlElement(name = "InternalPtyName")
    protected String internalPtyName;
    @XmlElement(name = "InternalPtyAddress")
    protected String internalPtyAddress;

    /**
     * Gets the value of the internalPtyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalPtyType() {
        return internalPtyType;
    }

    /**
     * Sets the value of the internalPtyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalPtyType(String value) {
        this.internalPtyType = value;
    }

    /**
     * Gets the value of the internalPtyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalPtyId() {
        return internalPtyId;
    }

    /**
     * Sets the value of the internalPtyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalPtyId(String value) {
        this.internalPtyId = value;
    }

    /**
     * Gets the value of the internalPtyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalPtyName() {
        return internalPtyName;
    }

    /**
     * Sets the value of the internalPtyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalPtyName(String value) {
        this.internalPtyName = value;
    }

    /**
     * Gets the value of the internalPtyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalPtyAddress() {
        return internalPtyAddress;
    }

    /**
     * Sets the value of the internalPtyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalPtyAddress(String value) {
        this.internalPtyAddress = value;
    }

}
