//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Party Type
 * 
 * <p>Java class for PARTYType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PARTYType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PartyQualifier" type="{http://www.rbcdexia.com}PartyQualifier-Type"/>
 *         &lt;element ref="{http://www.rbcdexia.com}BIC" minOccurs="0"/>
 *         &lt;element name="InternalParty" type="{http://www.rbcdexia.com}OTHERPARTYDEFINITIONType" minOccurs="0"/>
 *         &lt;element name="ClearingDetails" type="{http://www.rbcdexia.com}CLEARINGDETAILType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PartyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PartyAddress" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PartySafeAcct" minOccurs="0"/>
 *         &lt;element name="PartySubAcct" type="{http://www.rbcdexia.com}ACCOUNTType" minOccurs="0"/>
 *         &lt;element name="PartyCashAcct" type="{http://www.rbcdexia.com}ACCOUNTType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PARTYType", propOrder = {

})
public class PARTYType {

    @XmlElement(name = "PartyQualifier", required = true)
    protected PartyQualifierType partyQualifier;
    @XmlElement(name = "BIC")
    protected BICType bic;
    @XmlElement(name = "InternalParty")
    protected OTHERPARTYDEFINITIONType internalParty;
    @XmlElement(name = "ClearingDetails")
    protected CLEARINGDETAILType clearingDetails;
    @XmlElement(name = "PartyName")
    protected String partyName;
    @XmlElement(name = "PartyAddress")
    protected String partyAddress;
    @XmlElement(name = "PartySafeAcct")
    protected ACCOUNTType partySafeAcct;
    @XmlElement(name = "PartySubAcct")
    protected ACCOUNTType partySubAcct;
    @XmlElement(name = "PartyCashAcct")
    protected ACCOUNTType partyCashAcct;

    /**
     * Gets the value of the partyQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link PartyQualifierType }
     *     
     */
    public PartyQualifierType getPartyQualifier() {
        return partyQualifier;
    }

    /**
     * Sets the value of the partyQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyQualifierType }
     *     
     */
    public void setPartyQualifier(PartyQualifierType value) {
        this.partyQualifier = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link BICType }
     *     
     */
    public BICType getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BICType }
     *     
     */
    public void setBIC(BICType value) {
        this.bic = value;
    }

    /**
     * Gets the value of the internalParty property.
     * 
     * @return
     *     possible object is
     *     {@link OTHERPARTYDEFINITIONType }
     *     
     */
    public OTHERPARTYDEFINITIONType getInternalParty() {
        return internalParty;
    }

    /**
     * Sets the value of the internalParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTHERPARTYDEFINITIONType }
     *     
     */
    public void setInternalParty(OTHERPARTYDEFINITIONType value) {
        this.internalParty = value;
    }

    /**
     * Gets the value of the clearingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CLEARINGDETAILType }
     *     
     */
    public CLEARINGDETAILType getClearingDetails() {
        return clearingDetails;
    }

    /**
     * Sets the value of the clearingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLEARINGDETAILType }
     *     
     */
    public void setClearingDetails(CLEARINGDETAILType value) {
        this.clearingDetails = value;
    }

    /**
     * Gets the value of the partyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * Sets the value of the partyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyName(String value) {
        this.partyName = value;
    }

    /**
     * Gets the value of the partyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyAddress() {
        return partyAddress;
    }

    /**
     * Sets the value of the partyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyAddress(String value) {
        this.partyAddress = value;
    }

    /**
     * Gets the value of the partySafeAcct property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTType }
     *     
     */
    public ACCOUNTType getPartySafeAcct() {
        return partySafeAcct;
    }

    /**
     * Sets the value of the partySafeAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTType }
     *     
     */
    public void setPartySafeAcct(ACCOUNTType value) {
        this.partySafeAcct = value;
    }

    /**
     * Gets the value of the partySubAcct property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTType }
     *     
     */
    public ACCOUNTType getPartySubAcct() {
        return partySubAcct;
    }

    /**
     * Sets the value of the partySubAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTType }
     *     
     */
    public void setPartySubAcct(ACCOUNTType value) {
        this.partySubAcct = value;
    }

    /**
     * Gets the value of the partyCashAcct property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTType }
     *     
     */
    public ACCOUNTType getPartyCashAcct() {
        return partyCashAcct;
    }

    /**
     * Sets the value of the partyCashAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTType }
     *     
     */
    public void setPartyCashAcct(ACCOUNTType value) {
        this.partyCashAcct = value;
    }

}
