//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRICEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRICEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PriceCcy" type="{http://www.rbcdexia.com}A3" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}Price" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PriceType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PriceInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PriceValueInd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRICEType", propOrder = {
    "priceCcy",
    "price",
    "priceType",
    "priceInd",
    "priceValueInd"
})
public class PRICEType {

    @XmlElement(name = "PriceCcy")
    protected String priceCcy;
    @XmlElement(name = "Price")
    protected BigDecimal price;
    @XmlElement(name = "PriceType")
    protected String priceType;
    @XmlElement(name = "PriceInd")
    protected String priceInd;
    @XmlElement(name = "PriceValueInd")
    protected String priceValueInd;

    /**
     * Gets the value of the priceCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceCcy() {
        return priceCcy;
    }

    /**
     * Sets the value of the priceCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceCcy(String value) {
        this.priceCcy = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the priceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceType(String value) {
        this.priceType = value;
    }

    /**
     * Gets the value of the priceInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceInd() {
        return priceInd;
    }

    /**
     * Sets the value of the priceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceInd(String value) {
        this.priceInd = value;
    }

    /**
     * Gets the value of the priceValueInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceValueInd() {
        return priceValueInd;
    }

    /**
     * Sets the value of the priceValueInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceValueInd(String value) {
        this.priceValueInd = value;
    }

}
