//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Security Type
 * 
 * <p>Java class for SECURITYType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SECURITYType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.rbcdexia.com}SecuQualifier"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SecuValue"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SecuName" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SecuType" minOccurs="0"/>
 *         &lt;element name="DateDetails" type="{http://www.rbcdexia.com}DateType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}InterestRate" minOccurs="0"/>
 *         &lt;element name="DerivativesDtls" type="{http://www.rbcdexia.com}DERIVATIVESType" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SecuBlock" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}Override" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PoolFactor" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}AmortisedValue" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SECURITYType", propOrder = {

})
public class SECURITYType {

    @XmlElement(name = "SecuQualifier", required = true)
    protected String secuQualifier;
    @XmlElement(name = "SecuValue", required = true)
    protected String secuValue;
    @XmlElement(name = "SecuName")
    protected String secuName;
    @XmlElement(name = "SecuType")
    protected String secuType;
    @XmlElement(name = "DateDetails")
    protected DateType dateDetails;
    @XmlElement(name = "InterestRate")
    protected BigDecimal interestRate;
    @XmlElement(name = "DerivativesDtls")
    protected DERIVATIVESType derivativesDtls;
    @XmlElement(name = "SecuBlock")
    protected YNType secuBlock;
    @XmlElement(name = "Override")
    protected YNType override;
    @XmlElement(name = "PoolFactor")
    protected BigDecimal poolFactor;
    @XmlElement(name = "AmortisedValue")
    protected BigDecimal amortisedValue;

    /**
     * Gets the value of the secuQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuQualifier() {
        return secuQualifier;
    }

    /**
     * Sets the value of the secuQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuQualifier(String value) {
        this.secuQualifier = value;
    }

    /**
     * Gets the value of the secuValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuValue() {
        return secuValue;
    }

    /**
     * Sets the value of the secuValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuValue(String value) {
        this.secuValue = value;
    }

    /**
     * Gets the value of the secuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuName() {
        return secuName;
    }

    /**
     * Sets the value of the secuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuName(String value) {
        this.secuName = value;
    }

    /**
     * Gets the value of the secuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuType() {
        return secuType;
    }

    /**
     * Sets the value of the secuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuType(String value) {
        this.secuType = value;
    }

    /**
     * Gets the value of the dateDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDateDetails() {
        return dateDetails;
    }

    /**
     * Sets the value of the dateDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDateDetails(DateType value) {
        this.dateDetails = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the derivativesDtls property.
     * 
     * @return
     *     possible object is
     *     {@link DERIVATIVESType }
     *     
     */
    public DERIVATIVESType getDerivativesDtls() {
        return derivativesDtls;
    }

    /**
     * Sets the value of the derivativesDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link DERIVATIVESType }
     *     
     */
    public void setDerivativesDtls(DERIVATIVESType value) {
        this.derivativesDtls = value;
    }

    /**
     * Gets the value of the secuBlock property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getSecuBlock() {
        return secuBlock;
    }

    /**
     * Sets the value of the secuBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setSecuBlock(YNType value) {
        this.secuBlock = value;
    }

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getOverride() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setOverride(YNType value) {
        this.override = value;
    }

    /**
     * Gets the value of the poolFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPoolFactor() {
        return poolFactor;
    }

    /**
     * Sets the value of the poolFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPoolFactor(BigDecimal value) {
        this.poolFactor = value;
    }

    /**
     * Gets the value of the amortisedValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmortisedValue() {
        return amortisedValue;
    }

    /**
     * Sets the value of the amortisedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmortisedValue(BigDecimal value) {
        this.amortisedValue = value;
    }

}
