//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Place Of Settlement Type : The market where the trade will settle. This will drive the Clearing House options available in the Party sections.
 * 
 * <p>Java class for SETTLEMENTPLACEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SETTLEMENTPLACEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.rbcdexia.com}BIC" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SttlmCtryPlace" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}SttlmPlaceMethod" minOccurs="0"/>
 *         &lt;element ref="{http://www.rbcdexia.com}PhysicalIndicator" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SETTLEMENTPLACEType", propOrder = {

})
public class SETTLEMENTPLACEType {

    @XmlElement(name = "BIC")
    protected BICType bic;
    @XmlElement(name = "SttlmCtryPlace")
    protected String sttlmCtryPlace;
    @XmlElement(name = "SttlmPlaceMethod")
    protected String sttlmPlaceMethod;
    @XmlElement(name = "PhysicalIndicator")
    protected YNType physicalIndicator;

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link BICType }
     *     
     */
    public BICType getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BICType }
     *     
     */
    public void setBIC(BICType value) {
        this.bic = value;
    }

    /**
     * Gets the value of the sttlmCtryPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSttlmCtryPlace() {
        return sttlmCtryPlace;
    }

    /**
     * Sets the value of the sttlmCtryPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSttlmCtryPlace(String value) {
        this.sttlmCtryPlace = value;
    }

    /**
     * Gets the value of the sttlmPlaceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSttlmPlaceMethod() {
        return sttlmPlaceMethod;
    }

    /**
     * Sets the value of the sttlmPlaceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSttlmPlaceMethod(String value) {
        this.sttlmPlaceMethod = value;
    }

    /**
     * Gets the value of the physicalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getPhysicalIndicator() {
        return physicalIndicator;
    }

    /**
     * Sets the value of the physicalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setPhysicalIndicator(YNType value) {
        this.physicalIndicator = value;
    }

}
