//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxAndFeesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxAndFeesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxFeesQualifier" type="{http://www.rbcdexia.com}TaxFeesQualifier-Type"/>
 *         &lt;element name="TaxFeesCcy" type="{http://www.rbcdexia.com}A3" minOccurs="0"/>
 *         &lt;element name="TaxFeesAmtValue" type="{http://www.rbcdexia.com}N" minOccurs="0"/>
 *         &lt;element name="TaxFeesRate" type="{http://www.rbcdexia.com}N" minOccurs="0"/>
 *         &lt;element name="TaxFeesCode" type="{http://www.rbcdexia.com}A" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAndFeesType", propOrder = {
    "taxFeesQualifier",
    "taxFeesCcy",
    "taxFeesAmtValue",
    "taxFeesRate",
    "taxFeesCode"
})
public class TaxAndFeesType {

    @XmlElement(name = "TaxFeesQualifier", required = true)
    protected TaxFeesQualifierType taxFeesQualifier;
    @XmlElement(name = "TaxFeesCcy")
    protected String taxFeesCcy;
    @XmlElement(name = "TaxFeesAmtValue")
    protected BigDecimal taxFeesAmtValue;
    @XmlElement(name = "TaxFeesRate")
    protected BigDecimal taxFeesRate;
    @XmlElement(name = "TaxFeesCode")
    protected String taxFeesCode;

    /**
     * Gets the value of the taxFeesQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link TaxFeesQualifierType }
     *     
     */
    public TaxFeesQualifierType getTaxFeesQualifier() {
        return taxFeesQualifier;
    }

    /**
     * Sets the value of the taxFeesQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxFeesQualifierType }
     *     
     */
    public void setTaxFeesQualifier(TaxFeesQualifierType value) {
        this.taxFeesQualifier = value;
    }

    /**
     * Gets the value of the taxFeesCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxFeesCcy() {
        return taxFeesCcy;
    }

    /**
     * Sets the value of the taxFeesCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxFeesCcy(String value) {
        this.taxFeesCcy = value;
    }

    /**
     * Gets the value of the taxFeesAmtValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxFeesAmtValue() {
        return taxFeesAmtValue;
    }

    /**
     * Sets the value of the taxFeesAmtValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxFeesAmtValue(BigDecimal value) {
        this.taxFeesAmtValue = value;
    }

    /**
     * Gets the value of the taxFeesRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxFeesRate() {
        return taxFeesRate;
    }

    /**
     * Sets the value of the taxFeesRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxFeesRate(BigDecimal value) {
        this.taxFeesRate = value;
    }

    /**
     * Gets the value of the taxFeesCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxFeesCode() {
        return taxFeesCode;
    }

    /**
     * Sets the value of the taxFeesCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxFeesCode(String value) {
        this.taxFeesCode = value;
    }

}
