//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.rbcdexia.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitQualifier-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitQualifier-Type">
 *   &lt;restriction base="{http://www.rbcdexia.com}A">
 *     &lt;enumeration value="Rate"/>
 *     &lt;enumeration value="Qty"/>
 *     &lt;enumeration value="RemainQty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitQualifier-Type")
@XmlEnum
public enum UnitQualifierType {

    @XmlEnumValue("Rate")
    RATE("Rate"),
    @XmlEnumValue("Qty")
    QTY("Qty"),
    @XmlEnumValue("RemainQty")
    REMAIN_QTY("RemainQty");
    private final String value;

    UnitQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitQualifierType fromValue(String v) {
        for (UnitQualifierType c: UnitQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
