//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Account Definition Type
 * 
 * <p>Java class for ACCOUNTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCOUNTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.karshan.com}AccountCode" minOccurs="0"/>
 *         &lt;element name="AccountDef" type="{http://www.karshan.com}ACCOUNTIDType"/>
 *         &lt;element ref="{http://www.karshan.com}AccountName" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}AccountCcy" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCOUNTType", propOrder = {

})
public class ACCOUNTType {

    @XmlElement(name = "AccountCode")
    protected String accountCode;
    @XmlElement(name = "AccountDef", required = true)
    protected ACCOUNTIDType accountDef;
    @XmlElement(name = "AccountName")
    protected String accountName;
    @XmlElement(name = "AccountCcy")
    protected String accountCcy;

    /**
     * Gets the value of the accountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCode(String value) {
        this.accountCode = value;
    }

    /**
     * Gets the value of the accountDef property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTIDType }
     *     
     */
    public ACCOUNTIDType getAccountDef() {
        return accountDef;
    }

    /**
     * Sets the value of the accountDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTIDType }
     *     
     */
    public void setAccountDef(ACCOUNTIDType value) {
        this.accountDef = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCcy() {
        return accountCcy;
    }

    /**
     * Sets the value of the accountCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCcy(String value) {
        this.accountCcy = value;
    }

}
