//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * All informations regarding Allocation details of the trade
 * 
 * <p>Java class for AllocationBlockDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllocationBlockDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BulkAccount" type="{http://www.karshan.com}ACCOUNTType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}Allocation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllocationBlockDetailsType", propOrder = {
    "bulkAccount",
    "allocation"
})
public class AllocationBlockDetailsType {

    @XmlElement(name = "BulkAccount")
    protected ACCOUNTType bulkAccount;
    @XmlElement(name = "Allocation")
    protected List<Allocation> allocation;

    /**
     * Gets the value of the bulkAccount property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTType }
     *     
     */
    public ACCOUNTType getBulkAccount() {
        return bulkAccount;
    }

    /**
     * Sets the value of the bulkAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTType }
     *     
     */
    public void setBulkAccount(ACCOUNTType value) {
        this.bulkAccount = value;
    }

    /**
     * Gets the value of the allocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Allocation }
     * 
     * 
     */
    public List<Allocation> getAllocation() {
        if (allocation == null) {
            allocation = new ArrayList<Allocation>();
        }
        return this.allocation;
    }

}
