//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmtQualifier-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmtQualifier-Type">
 *   &lt;restriction base="{http://www.karshan.com}A">
 *     &lt;enumeration value="NetAmt"/>
 *     &lt;enumeration value="RoundedNetAmt"/>
 *     &lt;enumeration value="SttlmAmt"/>
 *     &lt;enumeration value="GrssAmt"/>
 *     &lt;enumeration value="AccrInterestAmt"/>
 *     &lt;enumeration value="BuyAmt"/>
 *     &lt;enumeration value="SellAmt"/>
 *     &lt;enumeration value="AmortizationAmt"/>
 *     &lt;enumeration value="PIKNetAmt"/>
 *     &lt;enumeration value="PIKGrssAmt"/>
 *     &lt;enumeration value="CashAmt"/>
 *     &lt;enumeration value="NetLendingAmt"/>
 *     &lt;enumeration value="InitMarginAmt"/>
 *     &lt;enumeration value="ProvisionAmt"/>
 *     &lt;enumeration value="CapitalAmt"/>
 *     &lt;enumeration value="UpFrontAmt"/>
 *     &lt;enumeration value="NominalAmt"/>
 *     &lt;enumeration value="PayAmt"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmtQualifier-Type")
@XmlEnum
public enum AmtQualifierType {

    @XmlEnumValue("NetAmt")
    NET_AMT("NetAmt"),
    @XmlEnumValue("RoundedNetAmt")
    ROUNDED_NET_AMT("RoundedNetAmt"),
    @XmlEnumValue("SttlmAmt")
    STTLM_AMT("SttlmAmt"),
    @XmlEnumValue("GrssAmt")
    GRSS_AMT("GrssAmt"),
    @XmlEnumValue("AccrInterestAmt")
    ACCR_INTEREST_AMT("AccrInterestAmt"),
    @XmlEnumValue("BuyAmt")
    BUY_AMT("BuyAmt"),
    @XmlEnumValue("SellAmt")
    SELL_AMT("SellAmt"),
    @XmlEnumValue("AmortizationAmt")
    AMORTIZATION_AMT("AmortizationAmt"),
    @XmlEnumValue("PIKNetAmt")
    PIK_NET_AMT("PIKNetAmt"),
    @XmlEnumValue("PIKGrssAmt")
    PIK_GRSS_AMT("PIKGrssAmt"),
    @XmlEnumValue("CashAmt")
    CASH_AMT("CashAmt"),
    @XmlEnumValue("NetLendingAmt")
    NET_LENDING_AMT("NetLendingAmt"),
    @XmlEnumValue("InitMarginAmt")
    INIT_MARGIN_AMT("InitMarginAmt"),
    @XmlEnumValue("ProvisionAmt")
    PROVISION_AMT("ProvisionAmt"),
    @XmlEnumValue("CapitalAmt")
    CAPITAL_AMT("CapitalAmt"),
    @XmlEnumValue("UpFrontAmt")
    UP_FRONT_AMT("UpFrontAmt"),
    @XmlEnumValue("NominalAmt")
    NOMINAL_AMT("NominalAmt"),
    @XmlEnumValue("PayAmt")
    PAY_AMT("PayAmt");
    private final String value;

    AmtQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmtQualifierType fromValue(String v) {
        for (AmtQualifierType c: AmtQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
