//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * PARTY Clearing Definition Type
 * 
 * <p>Java class for CLEARINGDETAILType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CLEARINGDETAILType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.karshan.com}ClearingCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ClearingName" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ClearingAccount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLEARINGDETAILType", propOrder = {
    "clearingCode",
    "clearingName",
    "clearingAccount"
})
public class CLEARINGDETAILType {

    @XmlElement(name = "ClearingCode")
    protected String clearingCode;
    @XmlElement(name = "ClearingName")
    protected String clearingName;
    @XmlElement(name = "ClearingAccount")
    protected ACCOUNTType clearingAccount;

    /**
     * Gets the value of the clearingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingCode() {
        return clearingCode;
    }

    /**
     * Sets the value of the clearingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingCode(String value) {
        this.clearingCode = value;
    }

    /**
     * Gets the value of the clearingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingName() {
        return clearingName;
    }

    /**
     * Sets the value of the clearingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingName(String value) {
        this.clearingName = value;
    }

    /**
     * Gets the value of the clearingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTType }
     *     
     */
    public ACCOUNTType getClearingAccount() {
        return clearingAccount;
    }

    /**
     * Sets the value of the clearingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTType }
     *     
     */
    public void setClearingAccount(ACCOUNTType value) {
        this.clearingAccount = value;
    }

}
