//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * OTC / Derivate Products Type
 * 
 * <p>Java class for DERIVATIVESType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DERIVATIVESType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateDtls" type="{http://www.karshan.com}DateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}OptType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}OptStyle" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}StrikePrice" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ContractSize" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ExchPlace" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}QuotPlace" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ProductType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DERIVATIVESType", propOrder = {
    "dateDtls",
    "optType",
    "optStyle",
    "strikePrice",
    "contractSize",
    "exchPlace",
    "quotPlace",
    "productType"
})
public class DERIVATIVESType {

    @XmlElement(name = "DateDtls")
    protected List<DateType> dateDtls;
    @XmlElement(name = "OptType")
    protected String optType;
    @XmlElement(name = "OptStyle")
    protected String optStyle;
    @XmlElement(name = "StrikePrice")
    protected BigDecimal strikePrice;
    @XmlElement(name = "ContractSize")
    protected BigDecimal contractSize;
    @XmlElement(name = "ExchPlace")
    protected String exchPlace;
    @XmlElement(name = "QuotPlace")
    protected String quotPlace;
    @XmlElement(name = "ProductType")
    protected YNType productType;

    /**
     * Gets the value of the dateDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDateDtls() {
        if (dateDtls == null) {
            dateDtls = new ArrayList<DateType>();
        }
        return this.dateDtls;
    }

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptType(String value) {
        this.optType = value;
    }

    /**
     * Gets the value of the optStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptStyle() {
        return optStyle;
    }

    /**
     * Sets the value of the optStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptStyle(String value) {
        this.optStyle = value;
    }

    /**
     * Gets the value of the strikePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStrikePrice() {
        return strikePrice;
    }

    /**
     * Sets the value of the strikePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStrikePrice(BigDecimal value) {
        this.strikePrice = value;
    }

    /**
     * Gets the value of the contractSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getContractSize() {
        return contractSize;
    }

    /**
     * Sets the value of the contractSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setContractSize(BigDecimal value) {
        this.contractSize = value;
    }

    /**
     * Gets the value of the exchPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchPlace() {
        return exchPlace;
    }

    /**
     * Sets the value of the exchPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchPlace(String value) {
        this.exchPlace = value;
    }

    /**
     * Gets the value of the quotPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotPlace() {
        return quotPlace;
    }

    /**
     * Sets the value of the quotPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotPlace(String value) {
        this.quotPlace = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setProductType(YNType value) {
        this.productType = value;
    }

}
