//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Interest Type
 * 
 * <p>Java class for INTERESTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTERESTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.karshan.com}AccrInterestFlag" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}DaysOfAccrInterest" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}InterestRate" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}RateType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}InterestRateType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}CalculationMode" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}InterestCalcBase" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}FixedRate" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTERESTType", propOrder = {

})
public class INTERESTType {

    @XmlElement(name = "AccrInterestFlag")
    protected YNType accrInterestFlag;
    @XmlElement(name = "DaysOfAccrInterest")
    protected Integer daysOfAccrInterest;
    @XmlElement(name = "InterestRate")
    protected BigDecimal interestRate;
    @XmlElement(name = "RateType")
    protected String rateType;
    @XmlElement(name = "InterestRateType")
    protected String interestRateType;
    @XmlElement(name = "CalculationMode")
    protected String calculationMode;
    @XmlElement(name = "InterestCalcBase")
    protected String interestCalcBase;
    @XmlElement(name = "FixedRate")
    protected BigDecimal fixedRate;

    /**
     * Gets the value of the accrInterestFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getAccrInterestFlag() {
        return accrInterestFlag;
    }

    /**
     * Sets the value of the accrInterestFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setAccrInterestFlag(YNType value) {
        this.accrInterestFlag = value;
    }

    /**
     * Gets the value of the daysOfAccrInterest property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysOfAccrInterest() {
        return daysOfAccrInterest;
    }

    /**
     * Sets the value of the daysOfAccrInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysOfAccrInterest(Integer value) {
        this.daysOfAccrInterest = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the rateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * Sets the value of the rateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateType(String value) {
        this.rateType = value;
    }

    /**
     * Gets the value of the interestRateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestRateType() {
        return interestRateType;
    }

    /**
     * Sets the value of the interestRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestRateType(String value) {
        this.interestRateType = value;
    }

    /**
     * Gets the value of the calculationMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationMode() {
        return calculationMode;
    }

    /**
     * Sets the value of the calculationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationMode(String value) {
        this.calculationMode = value;
    }

    /**
     * Gets the value of the interestCalcBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestCalcBase() {
        return interestCalcBase;
    }

    /**
     * Sets the value of the interestCalcBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestCalcBase(String value) {
        this.interestCalcBase = value;
    }

    /**
     * Gets the value of the fixedRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFixedRate() {
        return fixedRate;
    }

    /**
     * Sets the value of the fixedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFixedRate(BigDecimal value) {
        this.fixedRate = value;
    }

}
