//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Linkage Type
 * 
 * <p>Java class for LINKAGEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LINKAGEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Cancel" type="{http://www.karshan.com}CANCELType" minOccurs="0"/>
 *         &lt;element name="LinkedDeals" type="{http://www.karshan.com}LINKEDDEALType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}LinkageType" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}LinkedTradeRef" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LINKAGEType", propOrder = {

})
public class LINKAGEType {

    @XmlElement(name = "Cancel")
    protected CANCELType cancel;
    @XmlElement(name = "LinkedDeals")
    protected LINKEDDEALType linkedDeals;
    @XmlElement(name = "LinkageType")
    protected String linkageType;
    @XmlElement(name = "LinkedTradeRef")
    protected String linkedTradeRef;

    /**
     * Gets the value of the cancel property.
     * 
     * @return
     *     possible object is
     *     {@link CANCELType }
     *     
     */
    public CANCELType getCancel() {
        return cancel;
    }

    /**
     * Sets the value of the cancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CANCELType }
     *     
     */
    public void setCancel(CANCELType value) {
        this.cancel = value;
    }

    /**
     * Gets the value of the linkedDeals property.
     * 
     * @return
     *     possible object is
     *     {@link LINKEDDEALType }
     *     
     */
    public LINKEDDEALType getLinkedDeals() {
        return linkedDeals;
    }

    /**
     * Sets the value of the linkedDeals property.
     * 
     * @param value
     *     allowed object is
     *     {@link LINKEDDEALType }
     *     
     */
    public void setLinkedDeals(LINKEDDEALType value) {
        this.linkedDeals = value;
    }

    /**
     * Gets the value of the linkageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkageType() {
        return linkageType;
    }

    /**
     * Sets the value of the linkageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkageType(String value) {
        this.linkageType = value;
    }

    /**
     * Gets the value of the linkedTradeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedTradeRef() {
        return linkedTradeRef;
    }

    /**
     * Sets the value of the linkedTradeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedTradeRef(String value) {
        this.linkedTradeRef = value;
    }

}
