//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyQualifier-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyQualifier-Type">
 *   &lt;restriction base="{http://www.karshan.com}A">
 *     &lt;enumeration value="Broker"/>
 *     &lt;enumeration value="SubCustodian"/>
 *     &lt;enumeration value="DlvrrsAgt"/>
 *     &lt;enumeration value="DlvrrsCtdn"/>
 *     &lt;enumeration value="DlvrrsIntrmy"/>
 *     &lt;enumeration value="CashCorresp"/>
 *     &lt;enumeration value="PurchaseCashCorresp"/>
 *     &lt;enumeration value="SaleCashCorresp"/>
 *     &lt;enumeration value="DebitCashCorresp"/>
 *     &lt;enumeration value="CreditCashCorresp"/>
 *     &lt;enumeration value="PurchaseSubCustodian"/>
 *     &lt;enumeration value="SaleSubCustodian"/>
 *     &lt;enumeration value="BeneficiaryInst"/>
 *     &lt;enumeration value="AccountWithInst"/>
 *     &lt;enumeration value="IntrmyInst"/>
 *     &lt;enumeration value="ReceiverCorresp"/>
 *     &lt;enumeration value="BrokerCtdn"/>
 *     &lt;enumeration value="BrokerIntrmy"/>
 *     &lt;enumeration value="Custodian"/>
 *     &lt;enumeration value="IssuerGuaranteed"/>
 *     &lt;enumeration value="Counterparty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartyQualifier-Type")
@XmlEnum
public enum PartyQualifierType {

    @XmlEnumValue("Broker")
    BROKER("Broker"),
    @XmlEnumValue("SubCustodian")
    SUB_CUSTODIAN("SubCustodian"),
    @XmlEnumValue("DlvrrsAgt")
    DLVRRS_AGT("DlvrrsAgt"),
    @XmlEnumValue("DlvrrsCtdn")
    DLVRRS_CTDN("DlvrrsCtdn"),
    @XmlEnumValue("DlvrrsIntrmy")
    DLVRRS_INTRMY("DlvrrsIntrmy"),
    @XmlEnumValue("CashCorresp")
    CASH_CORRESP("CashCorresp"),
    @XmlEnumValue("PurchaseCashCorresp")
    PURCHASE_CASH_CORRESP("PurchaseCashCorresp"),
    @XmlEnumValue("SaleCashCorresp")
    SALE_CASH_CORRESP("SaleCashCorresp"),
    @XmlEnumValue("DebitCashCorresp")
    DEBIT_CASH_CORRESP("DebitCashCorresp"),
    @XmlEnumValue("CreditCashCorresp")
    CREDIT_CASH_CORRESP("CreditCashCorresp"),
    @XmlEnumValue("PurchaseSubCustodian")
    PURCHASE_SUB_CUSTODIAN("PurchaseSubCustodian"),
    @XmlEnumValue("SaleSubCustodian")
    SALE_SUB_CUSTODIAN("SaleSubCustodian"),
    @XmlEnumValue("BeneficiaryInst")
    BENEFICIARY_INST("BeneficiaryInst"),
    @XmlEnumValue("AccountWithInst")
    ACCOUNT_WITH_INST("AccountWithInst"),
    @XmlEnumValue("IntrmyInst")
    INTRMY_INST("IntrmyInst"),
    @XmlEnumValue("ReceiverCorresp")
    RECEIVER_CORRESP("ReceiverCorresp"),
    @XmlEnumValue("BrokerCtdn")
    BROKER_CTDN("BrokerCtdn"),
    @XmlEnumValue("BrokerIntrmy")
    BROKER_INTRMY("BrokerIntrmy"),
    @XmlEnumValue("Custodian")
    CUSTODIAN("Custodian"),
    @XmlEnumValue("IssuerGuaranteed")
    ISSUER_GUARANTEED("IssuerGuaranteed"),
    @XmlEnumValue("Counterparty")
    COUNTERPARTY("Counterparty");
    private final String value;

    PartyQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyQualifierType fromValue(String v) {
        for (PartyQualifierType c: PartyQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
