//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxFeesQualifier-Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaxFeesQualifier-Type">
 *   &lt;restriction base="{http://www.karshan.com}A">
 *     &lt;enumeration value="BrokerFees"/>
 *     &lt;enumeration value="TaxFees"/>
 *     &lt;enumeration value="StampFees"/>
 *     &lt;enumeration value="OtherFees"/>
 *     &lt;enumeration value="VAT"/>
 *     &lt;enumeration value="CustodianFees"/>
 *     &lt;enumeration value="SubCustodianFees"/>
 *     &lt;enumeration value="TaxAmt"/>
 *     &lt;enumeration value="RedemptionFees"/>
 *     &lt;enumeration value="RefundableRights"/>
 *     &lt;enumeration value="UnrefundableRights"/>
 *     &lt;enumeration value="RefundableFees"/>
 *     &lt;enumeration value="UnrefundableFees"/>
 *     &lt;enumeration value="PIKFees"/>
 *     &lt;enumeration value="CorrespFees"/>
 *     &lt;enumeration value="ClearingFees"/>
 *     &lt;enumeration value="ClearingHouseFees"/>
 *     &lt;enumeration value="InterestTaxAmt"/>
 *     &lt;enumeration value="CorrespCommissionFees"/>
 *     &lt;enumeration value="TerminationFeePayable"/>
 *     &lt;enumeration value="TerminationFeeReceivable"/>
 *     &lt;enumeration value="TerminationFeeNetValue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TaxFeesQualifier-Type")
@XmlEnum
public enum TaxFeesQualifierType {

    @XmlEnumValue("BrokerFees")
    BROKER_FEES("BrokerFees"),
    @XmlEnumValue("AccrInterestAmt")
    ACCR_INTEREST_FEES("AccrInterestAmt"),
    @XmlEnumValue("TaxFees")
    TAX_FEES("TaxFees"),
    @XmlEnumValue("StampFees")
    STAMP_FEES("StampFees"),
    @XmlEnumValue("OtherFees")
    OTHER_FEES("OtherFees"),
    VAT("VAT"),
    @XmlEnumValue("CustodianFees")
    CUSTODIAN_FEES("CustodianFees"),
    @XmlEnumValue("SubCustodianFees")
    SUB_CUSTODIAN_FEES("SubCustodianFees"),
    @XmlEnumValue("TaxAmt")
    TAX_AMT("TaxAmt"),
    @XmlEnumValue("RedemptionFees")
    REDEMPTION_FEES("RedemptionFees"),
    @XmlEnumValue("RefundableRights")
    REFUNDABLE_RIGHTS("RefundableRights"),
    @XmlEnumValue("UnrefundableRights")
    UNREFUNDABLE_RIGHTS("UnrefundableRights"),
    @XmlEnumValue("RefundableFees")
    REFUNDABLE_FEES("RefundableFees"),
    @XmlEnumValue("UnrefundableFees")
    UNREFUNDABLE_FEES("UnrefundableFees"),
    @XmlEnumValue("PIKFees")
    PIK_FEES("PIKFees"),
    @XmlEnumValue("CorrespFees")
    CORRESP_FEES("CorrespFees"),
    @XmlEnumValue("ClearingFees")
    CLEARING_FEES("ClearingFees"),
    @XmlEnumValue("ClearingHouseFees")
    CLEARING_HOUSE_FEES("ClearingHouseFees"),
    @XmlEnumValue("InterestTaxAmt")
    INTEREST_TAX_AMT("InterestTaxAmt"),
    @XmlEnumValue("CorrespCommissionFees")
    CORRESP_COMMISSION_FEES("CorrespCommissionFees"),
    @XmlEnumValue("TerminationFeePayable")
    TERMINATION_FEE_PAYABLE("TerminationFeePayable"),
    @XmlEnumValue("TerminationFeeReceivable")
    TERMINATION_FEE_RECEIVABLE("TerminationFeeReceivable"),
    @XmlEnumValue("TerminationFeeNetValue")
    TERMINATION_FEE_NET_VALUE("TerminationFeeNetValue");
    private final String value;

    TaxFeesQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TaxFeesQualifierType fromValue(String v) {
        for (TaxFeesQualifierType c: TaxFeesQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
