//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.22 at 04:41:15 PM IST 
//


package com.karshan.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Transaction Type
 * 
 * <p>Java class for TRANSACTIONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRANSACTIONType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.karshan.com}Action" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}Domain" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}OperationType" minOccurs="0"/>
 *         &lt;element name="ConfirmFlag" type="{http://www.karshan.com}YN-Type" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}ClientRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}BrokerRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}FundManagerCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.karshan.com}UserId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRANSACTIONType", propOrder = {
    "action",
    "domain",
    "operationType",
    "confirmFlag",
    "clientRef",
    "brokerRef",
    "fundManagerCode",
    "userId"
})
@XmlSeeAlso({
    AffirmationCustodyType.class
})
public class TRANSACTIONType {

    @XmlElement(name = "Action")
    protected String action;
    @XmlElement(name = "Domain")
    protected DomainType domain;
    @XmlElement(name = "OperationType")
    protected String operationType;
    @XmlElement(name = "ConfirmFlag")
    protected YNType confirmFlag;
    @XmlElement(name = "ClientRef")
    protected String clientRef;
    @XmlElement(name = "BrokerRef")
    protected String brokerRef;
    @XmlElement(name = "FundManagerCode")
    protected String fundManagerCode;
    @XmlElement(name = "UserId")
    protected String userId;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link DomainType }
     *     
     */
    public DomainType getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainType }
     *     
     */
    public void setDomain(DomainType value) {
        this.domain = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the confirmFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getConfirmFlag() {
        return confirmFlag;
    }

    /**
     * Sets the value of the confirmFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setConfirmFlag(YNType value) {
        this.confirmFlag = value;
    }

    /**
     * Gets the value of the clientRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientRef() {
        return clientRef;
    }

    /**
     * Sets the value of the clientRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientRef(String value) {
        this.clientRef = value;
    }

    /**
     * Gets the value of the brokerRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerRef() {
        return brokerRef;
    }

    /**
     * Sets the value of the brokerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerRef(String value) {
        this.brokerRef = value;
    }

    /**
     * Gets the value of the fundManagerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundManagerCode() {
        return fundManagerCode;
    }

    /**
     * Sets the value of the fundManagerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundManagerCode(String value) {
        this.fundManagerCode = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

}
